/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuMVC;

import actualizaciones.Actualizacion;
import actualizaciones.Vista;
import java.util.Observable;
import java.util.Observer;
import mensajes.Mensaje;

/**
 *
 * @author carlo
 */
public class VistaConfig extends javax.swing.JFrame implements Observer{

    int comodines;
    private static ControladorMenu controladorMenu;
    
    /**
     * Creates new form VistaConfig
     */
    public VistaConfig(ControladorMenu controladorMenu) {
        initComponents();
        this.controladorMenu = controladorMenu;
        rango13.setSelected(true);
    }
    
    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof String) {
            String comando = (String) arg;
            
            if (comando.equals("PARTIDA_CREADA")) {
                this.setVisible(true);
            } else if(comando.equals("PARTIDA_CONFIGURADA")) {
                this.dispose();
            }
        }
        
        if(arg instanceof Mensaje) {
            Mensaje mensaje = (Mensaje) arg;
            if(mensaje.getComando().equals("PARTIDA_CONFIGURADA")) {
                this.dispose();
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new utils.PanelRound();
        comodinesTxt = new javax.swing.JLabel();
        rango13 = new javax.swing.JRadioButton();
        rango10 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lessBtn = new utils.Btn();
        moreBtn = new utils.Btn();
        btn3 = new utils.Btn();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(128, 175, 167));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 243, 125));
        jLabel1.setText("RUMMY ROYALE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        panelRound1.setBackground(new java.awt.Color(82, 107, 103));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comodinesTxt.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        comodinesTxt.setForeground(new java.awt.Color(233, 243, 125));
        comodinesTxt.setText("4");
        panelRound1.add(comodinesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        rango13.setBackground(new java.awt.Color(82, 107, 103));
        buttonGroup1.add(rango13);
        rango13.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        rango13.setForeground(new java.awt.Color(255, 255, 255));
        rango13.setText("1-13");
        rango13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rango13ActionPerformed(evt);
            }
        });
        panelRound1.add(rango13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        rango10.setBackground(new java.awt.Color(82, 107, 103));
        buttonGroup1.add(rango10);
        rango10.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        rango10.setForeground(new java.awt.Color(255, 255, 255));
        rango10.setText("1-10");
        panelRound1.add(rango10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rango de fichas:");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Comodines:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        lessBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        lessBtn.setText("-");
        lessBtn.setRadius(5);
        lessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessBtnActionPerformed(evt);
            }
        });
        panelRound1.add(lessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 30, -1));

        moreBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        moreBtn.setText("+");
        moreBtn.setRadius(5);
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });
        panelRound1.add(moreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 30, -1));

        btn3.setBackground(new java.awt.Color(132, 145, 231));
        btn3.setBorder(null);
        btn3.setText("<html> <h1>Aceptar</h1> </html>");
        btn3.setBorderPainted(false);
        btn3.setColor(new java.awt.Color(132, 145, 231));
        btn3.setColorClick(new java.awt.Color(132, 118, 227));
        btn3.setColorOver(new java.awt.Color(132, 145, 231));
        btn3.setRadius(10);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panelRound1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 290, 50));

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 520, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rango13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rango13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rango13ActionPerformed

    private void lessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessBtnActionPerformed
        if (comodines > 2) {
            comodines--;
            comodinesTxt.setText(String.valueOf(comodines));
        }
    }//GEN-LAST:event_lessBtnActionPerformed

    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed

        if (comodines < 8) {
            comodines++;
            comodinesTxt.setText(String.valueOf(comodines));
        }
    }//GEN-LAST:event_moreBtnActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        int rango = rango13.isSelected() ? 13 : 10;
        controladorMenu.configurarPartida(comodines, rango);
    }//GEN-LAST:event_btn3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.Btn btn3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel comodinesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private utils.Btn lessBtn;
    private utils.Btn moreBtn;
    private utils.PanelRound panelRound1;
    private javax.swing.JRadioButton rango10;
    private javax.swing.JRadioButton rango13;
    // End of variables declaration//GEN-END:variables

   
}
