/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuMVC;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.Set;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author carloq
 */
public class VistaRegistro extends javax.swing.JFrame implements Observer {

    // private ControladorRegistro controlador;
    private ControladorMenu controladorMenu;
    private Color selectedColor1, selectedColor2, selectedColor3, selectedColor4;

    /**
     * Creates new form pruebaFrame
     */
    public VistaRegistro(ControladorMenu controladorMenu) {

        initComponents();
        this.controladorMenu = controladorMenu;
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof String) {
            String comando = (String) arg;

            if (comando.equals("PARTIDA_CONFIGURADA")) {
                this.setVisible(true);
            }
            if (comando.equals("JUGADOR_REGISTRADO")) {
                controladorMenu.mostrarTablero();
                this.dispose();
            }
//            if(comando.equals("JUGADOR_UNIDO")) {
//                this.setVisible(true);
//            }
        }
    }

    private class ColorChooserListener implements ActionListener {

        private int colorIndex;

        public ColorChooserListener(int index) {
            this.colorIndex = index;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            // mostrar selector
            Color newColor = JColorChooser.showDialog(null, "Seleccionar un color", Color.WHITE);

            if (newColor != null && isColorUnique(newColor)) {
                switch (colorIndex) {
                    case 1:
                        selectedColor1 = newColor;
                        colorPanel1.setBackground(selectedColor1);
                        break;
                    case 2:
                        selectedColor2 = newColor;
                        colorPanel2.setBackground(selectedColor2);
                        break;
                    case 3:
                        selectedColor3 = newColor;
                        colorPanel3.setBackground(selectedColor3);
                        break;
                    case 4:
                        selectedColor4 = newColor;
                        colorPanel4.setBackground(selectedColor4);
                        break;
                }
            } else if (newColor != null) {
                JOptionPane.showMessageDialog(null, "El color ya ha sido seleccionado.");
            }
        }

        private boolean isColorUnique(Color newColor) {
            Set<Color> selectedColors = new HashSet<>();
            if (selectedColor1 != null) {
                selectedColors.add(selectedColor1);
            }
            if (selectedColor2 != null) {
                selectedColors.add(selectedColor2);
            }
            if (selectedColor3 != null) {
                selectedColors.add(selectedColor3);
            }
            if (selectedColor4 != null) {
                selectedColors.add(selectedColor4);
            }
            return !selectedColors.contains(newColor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new utils.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        colorButton1 = new javax.swing.JButton();
        colorPanel1 = new javax.swing.JPanel();
        colorButton2 = new javax.swing.JButton();
        colorPanel2 = new javax.swing.JPanel();
        colorButton3 = new javax.swing.JButton();
        colorPanel3 = new javax.swing.JPanel();
        colorButton4 = new javax.swing.JButton();
        colorPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        avatar1 = new javax.swing.JRadioButton();
        avatar2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        avatar3 = new javax.swing.JRadioButton();
        avatar4 = new javax.swing.JRadioButton();
        lblAvatar2 = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        lblAvatar4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 175, 167));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 243, 125));
        jLabel1.setText("RUMMY ROYALE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        panelRound1.setBackground(new java.awt.Color(82, 107, 103));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AVAtar:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ReGISTRO");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        nombreTxt.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        nombreTxt.setBorder(null);
        panelRound1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 40));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("nombre:");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        startBtn.setBackground(new java.awt.Color(225, 240, 67));
        startBtn.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        startBtn.setText("start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        panelRound1.add(startBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 100, 40));

        colorButton1.setText("Color 1");
        colorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton1ActionPerformed(evt);
            }
        });
        panelRound1.add(colorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        javax.swing.GroupLayout colorPanel1Layout = new javax.swing.GroupLayout(colorPanel1);
        colorPanel1.setLayout(colorPanel1Layout);
        colorPanel1Layout.setHorizontalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorPanel1Layout.setVerticalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRound1.add(colorPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 70, 20));

        colorButton2.setText("Color 2");
        colorButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton2ActionPerformed(evt);
            }
        });
        panelRound1.add(colorButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        javax.swing.GroupLayout colorPanel2Layout = new javax.swing.GroupLayout(colorPanel2);
        colorPanel2.setLayout(colorPanel2Layout);
        colorPanel2Layout.setHorizontalGroup(
            colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorPanel2Layout.setVerticalGroup(
            colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRound1.add(colorPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 70, 20));

        colorButton3.setText("Color 3");
        colorButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton3ActionPerformed(evt);
            }
        });
        panelRound1.add(colorButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        javax.swing.GroupLayout colorPanel3Layout = new javax.swing.GroupLayout(colorPanel3);
        colorPanel3.setLayout(colorPanel3Layout);
        colorPanel3Layout.setHorizontalGroup(
            colorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorPanel3Layout.setVerticalGroup(
            colorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRound1.add(colorPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 70, 20));

        colorButton4.setText("Color 4");
        colorButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton4ActionPerformed(evt);
            }
        });
        panelRound1.add(colorButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        javax.swing.GroupLayout colorPanel4Layout = new javax.swing.GroupLayout(colorPanel4);
        colorPanel4.setLayout(colorPanel4Layout);
        colorPanel4Layout.setHorizontalGroup(
            colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorPanel4Layout.setVerticalGroup(
            colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRound1.add(colorPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 70, 20));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("colores:");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        avatar1.setBackground(new java.awt.Color(82, 107, 103));
        buttonGroup1.add(avatar1);
        avatar1.setForeground(new java.awt.Color(255, 255, 255));
        avatar1.setText("Creeper");
        avatar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatar1ActionPerformed(evt);
            }
        });
        panelRound1.add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        avatar2.setBackground(new java.awt.Color(82, 107, 103));
        buttonGroup1.add(avatar2);
        avatar2.setForeground(new java.awt.Color(255, 255, 255));
        avatar2.setText("Pig");
        avatar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatar2ActionPerformed(evt);
            }
        });
        panelRound1.add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel8.setText(".");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel2.setText(".");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        avatar3.setBackground(new java.awt.Color(82, 107, 103));
        buttonGroup1.add(avatar3);
        avatar3.setForeground(new java.awt.Color(255, 255, 255));
        avatar3.setText("Steve");
        avatar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatar3ActionPerformed(evt);
            }
        });
        panelRound1.add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        avatar4.setBackground(new java.awt.Color(82, 107, 103));
        buttonGroup1.add(avatar4);
        avatar4.setForeground(new java.awt.Color(255, 255, 255));
        avatar4.setText("Villager");
        panelRound1.add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        lblAvatar2.setText("lblAvatar2");
        panelRound1.add(lblAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        lblAvatar1.setText("lblAvatar1");
        panelRound1.add(lblAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblAvatar3.setText("lblAvatar2");
        panelRound1.add(lblAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        lblAvatar4.setText("lblAvatar2");
        panelRound1.add(lblAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 520, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void colorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton1ActionPerformed
        Color color = JColorChooser.showDialog(null, "Color de Ficha 1", Color.black);
        colorPanel1.setBackground(color);
        //int choosenColor = color.getRGB();
        // crear color con int: Color colorFromInt = new Color(choosenColor);
    }//GEN-LAST:event_colorButton1ActionPerformed

    private void colorButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton2ActionPerformed
        Color color = JColorChooser.showDialog(null, "Color de Ficha 2", Color.black);
        colorPanel2.setBackground(color);
        //int choosenColor = color.getRGB();
    }//GEN-LAST:event_colorButton2ActionPerformed

    private void colorButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton3ActionPerformed
        Color color = JColorChooser.showDialog(null, "Color de Ficha 3", Color.black);
        colorPanel3.setBackground(color);
        //int choosenColor = color.getRGB();
    }//GEN-LAST:event_colorButton3ActionPerformed

    private void colorButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton4ActionPerformed
        Color color = JColorChooser.showDialog(null, "Color de Ficha 3", Color.black);
        colorPanel4.setBackground(color);
        //int choosenColor = color.getRGB();
    }//GEN-LAST:event_colorButton4ActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed

        Color colorSeleccionado1 = colorPanel1.getBackground();
        Color colorSeleccionado2 = colorPanel2.getBackground();
        Color colorSeleccionado3 = colorPanel3.getBackground();
        Color colorSeleccionado4 = colorPanel4.getBackground();

        String nombre = nombreTxt.getText();

        String avatar = "";

        if (avatar1.isSelected()) {
            avatar = "creeper";
        } else if (avatar2.isSelected()) {
            avatar = "pig";
        } else if (avatar3.isSelected()) {
            avatar = "steve";
        } else if (avatar4.isSelected()) {
            avatar = "villager";
        } else {
            System.out.println("No fue seleccionado avatar");
        }
        controladorMenu.crearJugador(nombre, avatar, colorSeleccionado1, colorSeleccionado2, colorSeleccionado3, colorSeleccionado4);


    }//GEN-LAST:event_startBtnActionPerformed

    private void avatar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avatar1ActionPerformed

    private void avatar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avatar2ActionPerformed

    private void avatar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avatar3ActionPerformed

    private String obtenerAvatarSeleccionado() {
        if (avatar1.isSelected()) {
            return "avatar1";
        } else if (avatar2.isSelected()) {
            return "avatar2";
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaRegistro().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton avatar1;
    private javax.swing.JRadioButton avatar2;
    private javax.swing.JRadioButton avatar3;
    private javax.swing.JRadioButton avatar4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton colorButton1;
    private javax.swing.JButton colorButton2;
    private javax.swing.JButton colorButton3;
    private javax.swing.JButton colorButton4;
    private javax.swing.JPanel colorPanel1;
    private javax.swing.JPanel colorPanel2;
    private javax.swing.JPanel colorPanel3;
    private javax.swing.JPanel colorPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JTextField nombreTxt;
    private utils.PanelRound panelRound1;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
