package menuMVC;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author carlo
 */
public class VistaConfiguracion extends javax.swing.JPanel implements Observer {

    int comodines;
    private static ControladorMenu controladorMenu;

    /**
     * Creates new form View
     */
    public VistaConfiguracion(ControladorMenu controladorMenu) {
        initComponents();
        this.controladorMenu = controladorMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new utils.PanelRound();
        comodinesTxt = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lessBtn = new utils.Btn();
        moreBtn = new utils.Btn();
        btn3 = new utils.Btn();

        jPanel1.setBackground(new java.awt.Color(128, 175, 167));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 243, 125));
        jLabel1.setText("RUMMY ROYALE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        panelRound1.setBackground(new java.awt.Color(82, 107, 103));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comodinesTxt.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        comodinesTxt.setForeground(new java.awt.Color(233, 243, 125));
        comodinesTxt.setText("4");
        panelRound1.add(comodinesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("1-13");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        panelRound1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("1-10");
        panelRound1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rango de fichas:");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Comodines:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        lessBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        lessBtn.setText("-");
        lessBtn.setRadius(5);
        lessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessBtnActionPerformed(evt);
            }
        });
        panelRound1.add(lessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 30, -1));

        moreBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        moreBtn.setText("+");
        moreBtn.setRadius(5);
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });
        panelRound1.add(moreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 30, -1));

        btn3.setBackground(new java.awt.Color(132, 145, 231));
        btn3.setBorder(null);
        btn3.setText("<html>\n<h1>Crear nuevo juego</h1>\n</html>");
        btn3.setBorderPainted(false);
        btn3.setColor(new java.awt.Color(132, 145, 231));
        btn3.setColorClick(new java.awt.Color(132, 118, 227));
        btn3.setColorOver(new java.awt.Color(132, 145, 231));
        btn3.setRadius(10);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panelRound1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 290, 50));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 520, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void lessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessBtnActionPerformed
        if (comodines > 2) {
            comodines--;
            comodinesTxt.setText(String.valueOf(comodines));
        }

    }//GEN-LAST:event_lessBtnActionPerformed

    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed

        if (comodines < 8) {
            comodines++;
            comodinesTxt.setText(String.valueOf(comodines));
        }

    }//GEN-LAST:event_moreBtnActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.Btn btn3;
    private javax.swing.JLabel comodinesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private utils.Btn lessBtn;
    private utils.Btn moreBtn;
    private utils.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        System.out.println("Actualización recibida en VistaUnirse");

//        if (o instanceof ModeloMenu) {
//            ModeloMenu modeloUnirse = (ModeloMenu) o;
//            if (modeloUnirse.getJuego() != null) {
//
//            }
//        }
    }
}
